### ISSUE TITLE
Update APK on Github

### ISSUE THREAD

**Issue by IzzySoft** [calintat/Explorer#3]
Thanks for offering this great app for free – and even having the `.apk` available at Github! However, I've noticed that file is from June, while the latest release was in November. Could you make an update available here as well? Best place of course would be with the `releases/` page, see [Creating Releases](https://help.github.com/articles/creating-releases/) ;)

**Comment by calintat** [comment]
I just created a release for the v1.0.5 update which should be live on the Play Store now.
From now on, I will create new releases for each update and make sure to keep the `.apk` up-to-date.

**Comment by IzzySoft** [comment]
Thanks a lot! In that case, folks without Playstore can use the F-Droid client to install/update [from here](https://apt.izzysoft.de/fdroid/index/apk/com.calintat.explorer) :smiley_cat: Updates are usually available within 24h of your releasing them here at Github. People using the repo will then get notified automatically when their F-Droid client next updates its package lists.
