### ISSUE TITLE
Delete-all mishappenings with SE Text Editor and SwiftKey

### ISSUE THREAD

**Issue by 3l4d3** [calintat/explorer#6]
When using the SE Text Editor to edit raw text files with the SwiftKey keyboard, which has a swipe to left from anywhere feature to delete a whole word backwards (similar to ctrl+backspace on PC), the whole document gets deleted from the caret's current position to the beginning of the document. This is a hassle, as I'm quite used to the SwiftKey feature... I only have this problem with SE Text Editor, so I thought it worth mentioning.

**Comment by calintat** [comment]
This doesn't sound like a problem with Explorer. Could you please elaborate?

**Comment by 3l4d3** [comment]
No, it's not a problem with the Explorer, but the SE Text Editor that is bundled, among others, with the explorer. Have I posted in the wrong place?

**Comment by calintat** [comment]
No text editor is bundled with Explorer. Perhaps you’re referring to a different app.

**Comment by 3l4d3** [comment]
I'm sorry. I followed the Play Store link, and I was indeed referring to another app. Thanks for the quick response anyway.
